[package]
name = "app"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "napkin"
path = "src/main.rs"

[dependencies]
bytemuck.workspace = true
eframe.workspace = true
egui-wgpu.workspace = true
glyphon.workspace = true
lyon.workspace = true
raw-window-handle.workspace = true
rough.workspace = true
rustix.workspace = true
scene.workspace = true
serde_json.workspace = true
toml.workspace = true
wayland-backend.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wgpu.workspace = true

[dev-dependencies]
pollster.workspace = true
